*&---------------------------------------------------------------------*
*& Modulpool SAPBC414_TRAVELAG_T
*&---------------------------------------------------------------------*


INCLUDE ZTRAVELAG_01TOP.
*INCLUDE BC414_TRAVELAG_TTOP.
INCLUDE ZTRAVELAG_01F01.
*INCLUDE BC414_TRAVELAG_TF01.
INCLUDE ZTRAVELAG_01001.
*INCLUDE BC414_TRAVELAG_TO01.
INCLUDE ZTRAVELAG_01I01.
*INCLUDE BC414_TRAVELAG_TI01.
INCLUDE ZTRAVELAG_01E01.
*INCLUDE BC414_TRAVELAG_TE01.
